export default {
  products: [
    {
      _id: "1",
      name: "Leather Shoes",
      category: "Men",
      image: "/images/product-1.jpg",
      price: 12035,
      brand: "Shoemate",
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: "2",
      name: "Leather Shoes",
      category: "Men",
      image: "/images/product-4.jpg",
      price: 1850,
      brand: "Shoemate",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "3",
      name: "Leather Shoes",
      category: "Men",
      image: "/images/product-5.jpg",
      price: 1850,
      brand: "Shoemate",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "4",
      name: "Leather Shoes",
      category: "Men",
      image: "/images/product-6.jpg",
      price: 1850,
      brand: "Shoemate",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "5",
      name: "Leather Shoes",
      category: "Men",
      image: "/images/product-11.jpg",
      price: 1850,
      brand: "Shoemate",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "6",
      name: "Leather Shoes",
      category: "Men",
      image: "/images/product-4.jpg",
      price: 1850,
      brand: "Shoemate",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: "7",
      name: "Leather Shoes",
      category: "Men",
      image: "/images/product-6.jpg",
      price: 1850,
      brand: "Shoemate",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
  ],
};
